### ISSUE TITLE
Docs build error

### ISSUE THREAD

**Issue by jeroen** [ropensci/lightr#13]
After the end of every docs build we see this:
```
Error while shutting down parallel: unable to terminate some child processes
```

See: https://dev.ropensci.org/job/lightr/lastBuild/console

Do you think this is a bug in lightr or something in the build server? I'm not seeing this for any other packages right now.

**Comment by Bisaloo** [comment]
Yeah, I noticed that as well. It was working earlier today though.

It's probably something on my end because I get the same issue when building locally.

**Comment by jeroen** [comment]
There is also another issue that your docs are [deployed inside the /dev subdirectory](https://github.com/ropensci-docs/lightr), probably because your pkgdown.yml has:

```yml
development:
  mode: auto
```

Probably need to override this on the build server somehow ....

**Comment by Bisaloo** [comment]
Ah, I was actually trying to see if we could have two versions of the docs co-existing, as it is the case for `pkgdown` for example

https://pkgdown.r-lib.org/
https://pkgdown.r-lib.org/dev/

I guess it doesn't work here because you empty the folder every time(?)

**Comment by jeroen** [comment]
No sorry, right now we only publish a single pkgdown site, and each build overrides the previous one.

**Comment by Bisaloo** [comment]
So the issue reported in OP shouldn't prevent the docs from being built. It works locally and it was working before I bumped the version to `0.1.9000`, moving the docs to the dev folder.

The underlying issue seems to be with the `pbmcapply` since this warning vanishes on the `future` branch.
